package com.devloopsx.chronelis.constant;

public enum ActivityActionType {
    WORKSPACE_CREATED,
    WORKSPACE_UPDATED,
    MEMBER_ADDED,
    MEMBER_REMOVED,
    MEMBER_ROLE_UPDATED,
    PROJECT_CREATED,
    PROJECT_UPDATED,
    GOAL_CREATED,
    GOAL_UPDATED,
    GOAL_DELETED,
    TASK_CREATED,
    TASK_UPDATED,
    TASK_ASSIGNED,
    TASK_UNASSIGNED,
    TASK_RESCHEDULED,
    TASK_MOVED_STATUS,
    TASK_REORDERED,
    TASK_DELETED,
    COMMENT_ADDED,
    COMMENT_UPDATED,
    COMMENT_DELETED
}
